# Generated by Django 6.0.2 on 2026-04-02 07:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Р‘СЂРµРЅРґ', 'verbose_name_plural': 'Р‘СЂРµРЅРґС‹'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'РљР°С‚РµРіРѕСЂРёСЏ', 'verbose_name_plural': 'РљР°С‚РµРіРѕСЂРёРё'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'РўРѕРІР°СЂ', 'verbose_name_plural': 'РўРѕРІР°СЂС‹'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['name'], 'verbose_name': 'РџСЂРѕРґР°РІРµС†', 'verbose_name_plural': 'РџСЂРѕРґР°РІС†С‹'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name'], 'verbose_name': 'РњР°РіР°Р·РёРЅ', 'verbose_name_plural': 'РњР°РіР°Р·РёРЅС‹'},
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='РЎСЃС‹Р»РєР° РЅР° С„РѕС‚Рѕ'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='РќР°Р·РІР°РЅРёРµ Р±СЂРµРЅРґР°'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='catalog.shop', verbose_name='РњР°РіР°Р·РёРЅ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='РќР°Р·РІР°РЅРёРµ РєР°С‚РµРіРѕСЂРёРё'),
        ),
        migrations.AlterField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.shop', verbose_name='РњР°РіР°Р·РёРЅ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Р‘СЂРµРЅРґ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='РљР°С‚РµРіРѕСЂРёСЏ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='РћРїРёСЃР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='РќР°Р·РІР°РЅРёРµ С‚РѕРІР°СЂР°'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Р¦РµРЅР°'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.seller', verbose_name='РџСЂРѕРґР°РІРµС†'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.shop', verbose_name='РњР°РіР°Р·РёРЅ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='РћСЃС‚Р°С‚РѕРє'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Р›РѕРєР°С†РёСЏ'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=255, verbose_name='РџСЂРѕРґР°РІРµС†/С‚РѕС‡РєР°'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Р\xa0РµР№С‚РёРЅРі'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='catalog.shop', verbose_name='РњР°РіР°Р·РёРЅ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='РќР°Р·РІР°РЅРёРµ'),
        ),
    ]
